# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: finger1
  joint_model_group_pose: homef1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - bh_j11_joint
    - bh_j12_joint
    - bh_j13_joint
    - bh_j21_joint
    - bh_j22_joint
    - bh_j23_joint
    - bh_j32_joint
    - bh_j33_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []