controller_list:
  - name: fake_finger1_controller
    type: $(arg execution_type)
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
initial:  # Define initial robot poses.
  - group: finger1
    pose: home