controller_list:
  - name: fake_three_fingers_controller
    type: $(arg execution_type)
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
      - bh_j21_joint
      - bh_j22_joint
      - bh_j23_joint
      - bh_j32_joint
      - bh_j33_joint
initial:  # Define initial robot poses.
  - group: three_fingers
    pose: home